# https://github.com/nashpaz123/maven-hello-world

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: docker io
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'

- script: docker run docker.io/nashpaz1/maven-hello-world:17