# https://github.com/nashpaz123/maven-hello-world

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: mvn clean
  workingDirectory: my-app/
  displayName: '1. clean'

- script: mvn package && ls -l
  workingDirectory: my-app/
  displayName: '2. package and check files'
